# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\学校资料-彭卓立-20150708\这这这这课程\EC601\hw_1\GUI_test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1002, 663)
        self.pushButton_a = QtGui.QPushButton(Dialog)
        self.pushButton_a.setGeometry(QtCore.QRect(440, 470, 41, 41))
        self.pushButton_a.setObjectName(_fromUtf8("pushButton_a"))
        self.pushButton_q = QtGui.QPushButton(Dialog)
        self.pushButton_q.setGeometry(QtCore.QRect(420, 420, 41, 41))
        self.pushButton_q.setObjectName(_fromUtf8("pushButton_q"))
        self.pushButton_w = QtGui.QPushButton(Dialog)
        self.pushButton_w.setGeometry(QtCore.QRect(470, 420, 41, 41))
        self.pushButton_w.setObjectName(_fromUtf8("pushButton_w"))
        self.pushButton_r = QtGui.QPushButton(Dialog)
        self.pushButton_r.setGeometry(QtCore.QRect(570, 420, 41, 41))
        self.pushButton_r.setObjectName(_fromUtf8("pushButton_r"))
        self.pushButton_e = QtGui.QPushButton(Dialog)
        self.pushButton_e.setGeometry(QtCore.QRect(520, 420, 41, 41))
        self.pushButton_e.setObjectName(_fromUtf8("pushButton_e"))
        self.pushButton_t = QtGui.QPushButton(Dialog)
        self.pushButton_t.setGeometry(QtCore.QRect(620, 420, 41, 41))
        self.pushButton_t.setObjectName(_fromUtf8("pushButton_t"))
        self.pushButton_y = QtGui.QPushButton(Dialog)
        self.pushButton_y.setGeometry(QtCore.QRect(670, 420, 41, 41))
        self.pushButton_y.setObjectName(_fromUtf8("pushButton_y"))
        self.pushButton_u = QtGui.QPushButton(Dialog)
        self.pushButton_u.setGeometry(QtCore.QRect(720, 420, 41, 41))
        self.pushButton_u.setObjectName(_fromUtf8("pushButton_u"))
        self.pushButton_i = QtGui.QPushButton(Dialog)
        self.pushButton_i.setGeometry(QtCore.QRect(770, 420, 41, 41))
        self.pushButton_i.setObjectName(_fromUtf8("pushButton_i"))
        self.pushButton_o = QtGui.QPushButton(Dialog)
        self.pushButton_o.setGeometry(QtCore.QRect(820, 420, 41, 41))
        self.pushButton_o.setObjectName(_fromUtf8("pushButton_o"))
        self.pushButton_p = QtGui.QPushButton(Dialog)
        self.pushButton_p.setGeometry(QtCore.QRect(870, 420, 41, 41))
        self.pushButton_p.setObjectName(_fromUtf8("pushButton_p"))
        self.pushButton_s = QtGui.QPushButton(Dialog)
        self.pushButton_s.setGeometry(QtCore.QRect(490, 470, 41, 41))
        self.pushButton_s.setObjectName(_fromUtf8("pushButton_s"))
        self.pushButton_d = QtGui.QPushButton(Dialog)
        self.pushButton_d.setGeometry(QtCore.QRect(540, 470, 41, 41))
        self.pushButton_d.setObjectName(_fromUtf8("pushButton_d"))
        self.pushButton_f = QtGui.QPushButton(Dialog)
        self.pushButton_f.setGeometry(QtCore.QRect(590, 470, 41, 41))
        self.pushButton_f.setObjectName(_fromUtf8("pushButton_f"))
        self.pushButton_g = QtGui.QPushButton(Dialog)
        self.pushButton_g.setGeometry(QtCore.QRect(640, 470, 41, 41))
        self.pushButton_g.setObjectName(_fromUtf8("pushButton_g"))
        self.pushButton_j = QtGui.QPushButton(Dialog)
        self.pushButton_j.setGeometry(QtCore.QRect(740, 470, 41, 41))
        self.pushButton_j.setObjectName(_fromUtf8("pushButton_j"))
        self.pushButton_h = QtGui.QPushButton(Dialog)
        self.pushButton_h.setGeometry(QtCore.QRect(690, 470, 41, 41))
        self.pushButton_h.setObjectName(_fromUtf8("pushButton_h"))
        self.pushButton_z = QtGui.QPushButton(Dialog)
        self.pushButton_z.setGeometry(QtCore.QRect(460, 520, 41, 41))
        self.pushButton_z.setObjectName(_fromUtf8("pushButton_z"))
        self.pushButton_x = QtGui.QPushButton(Dialog)
        self.pushButton_x.setGeometry(QtCore.QRect(510, 520, 41, 41))
        self.pushButton_x.setObjectName(_fromUtf8("pushButton_x"))
        self.pushButton_c = QtGui.QPushButton(Dialog)
        self.pushButton_c.setGeometry(QtCore.QRect(560, 520, 41, 41))
        self.pushButton_c.setObjectName(_fromUtf8("pushButton_c"))
        self.pushButton_n = QtGui.QPushButton(Dialog)
        self.pushButton_n.setGeometry(QtCore.QRect(710, 520, 41, 41))
        self.pushButton_n.setObjectName(_fromUtf8("pushButton_n"))
        self.pushButton_b = QtGui.QPushButton(Dialog)
        self.pushButton_b.setGeometry(QtCore.QRect(660, 520, 41, 41))
        self.pushButton_b.setObjectName(_fromUtf8("pushButton_b"))
        self.pushButton_k = QtGui.QPushButton(Dialog)
        self.pushButton_k.setGeometry(QtCore.QRect(790, 470, 41, 41))
        self.pushButton_k.setObjectName(_fromUtf8("pushButton_k"))
        self.pushButton_v = QtGui.QPushButton(Dialog)
        self.pushButton_v.setGeometry(QtCore.QRect(610, 520, 41, 41))
        self.pushButton_v.setObjectName(_fromUtf8("pushButton_v"))
        self.pushButton_l = QtGui.QPushButton(Dialog)
        self.pushButton_l.setGeometry(QtCore.QRect(840, 470, 41, 41))
        self.pushButton_l.setObjectName(_fromUtf8("pushButton_l"))
        self.pushButton_m = QtGui.QPushButton(Dialog)
        self.pushButton_m.setGeometry(QtCore.QRect(760, 520, 41, 41))
        self.pushButton_m.setObjectName(_fromUtf8("pushButton_m"))
        self.picture = QtGui.QGraphicsView(Dialog)
        self.picture.setGeometry(QtCore.QRect(110, 140, 256, 381))
        self.picture.setObjectName(_fromUtf8("picture"))
        self.cityname = QtGui.QTextEdit(Dialog)
        self.cityname.setGeometry(QtCore.QRect(420, 140, 481, 191))
        self.cityname.setObjectName(_fromUtf8("cityname"))
        self.chancelefted = QtGui.QTextEdit(Dialog)
        self.chancelefted.setGeometry(QtCore.QRect(140, 540, 201, 41))
        self.chancelefted.setObjectName(_fromUtf8("chancelefted"))
        self.usedletter = QtGui.QTextEdit(Dialog)
        self.usedletter.setGeometry(QtCore.QRect(440, 340, 451, 41))
        self.usedletter.setObjectName(_fromUtf8("usedletter"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(450, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_q, self.pushButton_w)
        Dialog.setTabOrder(self.pushButton_w, self.pushButton_e)
        Dialog.setTabOrder(self.pushButton_e, self.pushButton_r)
        Dialog.setTabOrder(self.pushButton_r, self.pushButton_t)
        Dialog.setTabOrder(self.pushButton_t, self.pushButton_y)
        Dialog.setTabOrder(self.pushButton_y, self.pushButton_u)
        Dialog.setTabOrder(self.pushButton_u, self.pushButton_i)
        Dialog.setTabOrder(self.pushButton_i, self.pushButton_o)
        Dialog.setTabOrder(self.pushButton_o, self.pushButton_p)
        Dialog.setTabOrder(self.pushButton_p, self.pushButton_a)
        Dialog.setTabOrder(self.pushButton_a, self.pushButton_s)
        Dialog.setTabOrder(self.pushButton_s, self.pushButton_d)
        Dialog.setTabOrder(self.pushButton_d, self.pushButton_f)
        Dialog.setTabOrder(self.pushButton_f, self.pushButton_g)
        Dialog.setTabOrder(self.pushButton_g, self.pushButton_h)
        Dialog.setTabOrder(self.pushButton_h, self.pushButton_j)
        Dialog.setTabOrder(self.pushButton_j, self.pushButton_k)
        Dialog.setTabOrder(self.pushButton_k, self.pushButton_l)
        Dialog.setTabOrder(self.pushButton_l, self.pushButton_z)
        Dialog.setTabOrder(self.pushButton_z, self.pushButton_x)
        Dialog.setTabOrder(self.pushButton_x, self.pushButton_c)
        Dialog.setTabOrder(self.pushButton_c, self.pushButton_v)
        Dialog.setTabOrder(self.pushButton_v, self.pushButton_b)
        Dialog.setTabOrder(self.pushButton_b, self.pushButton_n)
        Dialog.setTabOrder(self.pushButton_n, self.pushButton_m)
        Dialog.setTabOrder(self.pushButton_m, self.picture)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.pushButton_a.setText(_translate("Dialog", "A", None))
        self.pushButton_q.setText(_translate("Dialog", "Q", None))
        self.pushButton_w.setText(_translate("Dialog", "W", None))
        self.pushButton_r.setText(_translate("Dialog", "R", None))
        self.pushButton_e.setText(_translate("Dialog", "E", None))
        self.pushButton_t.setText(_translate("Dialog", "T", None))
        self.pushButton_y.setText(_translate("Dialog", "Y", None))
        self.pushButton_u.setText(_translate("Dialog", "U", None))
        self.pushButton_i.setText(_translate("Dialog", "I", None))
        self.pushButton_o.setText(_translate("Dialog", "O", None))
        self.pushButton_p.setText(_translate("Dialog", "P", None))
        self.pushButton_s.setText(_translate("Dialog", "S", None))
        self.pushButton_d.setText(_translate("Dialog", "D", None))
        self.pushButton_f.setText(_translate("Dialog", "F", None))
        self.pushButton_g.setText(_translate("Dialog", "G", None))
        self.pushButton_j.setText(_translate("Dialog", "J", None))
        self.pushButton_h.setText(_translate("Dialog", "H", None))
        self.pushButton_z.setText(_translate("Dialog", "Z", None))
        self.pushButton_x.setText(_translate("Dialog", "X", None))
        self.pushButton_c.setText(_translate("Dialog", "C", None))
        self.pushButton_n.setText(_translate("Dialog", "N", None))
        self.pushButton_b.setText(_translate("Dialog", "B", None))
        self.pushButton_k.setText(_translate("Dialog", "K", None))
        self.pushButton_v.setText(_translate("Dialog", "V", None))
        self.pushButton_l.setText(_translate("Dialog", "L", None))
        self.pushButton_m.setText(_translate("Dialog", "M", None))
        self.label.setText(_translate("Dialog", "Hangman", None))

